//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deVoid.UIFramework.Examples {
    
    
    public sealed class ScreenIds {
        
        public const string DeathScreen = "DeathScreen";
        
        public const string EndScreen = "EndScreen";
        
        public const string HowToPlayScreen = "HowToPlayScreen";
        
        public const string MainMenuScreen = "MainMenuScreen";
        
        public const string PauseScreen = "PauseScreen";
        
        public const string SettingsScreen = "SettingsScreen";
    }
}
